more bash goodies

diff --git a/bash/scripts/.template b/bash/scripts/.template
--- a/bash/scripts/.template
+++ b/bash/scripts/.template
@@ -8,7 +8,7 @@ SCRIPT_NAME=$(basename "$0")
 # ==========================================
 
 fail() {
-    echo "${1-command failed}" >&2
+    echo "${1-$SCRIPT_NAME command failed}" >&2
     exit ${2:-1}
 }
 
@@ -53,6 +53,7 @@ prompt_yn() {
     done
     [ "$resp" = 'y' ] && return 0 || return 1
 }
+
 
 # collect args
 # ==========================================
