support for handling multiple branches for a ticket

diff --git a/bash/scripts/grev b/bash/scripts/grev
--- a/bash/scripts/grev
+++ b/bash/scripts/grev
@@ -10,13 +10,13 @@ fail() {
 
 usage() {
         cat <<EOI
-usage: $SCRIPT_NAME [ARGS] TICKET_NUM
+usage: $SCRIPT_NAME [ARGS] TICKET_NUM [BRANCH_INDEX]
 
-Checks out a git branch based on a "\$initials/\$ticket/\$description" branch naming convention.
+Checks out a git branch based on a "\$initials/\$ticket/\$description" branch naming convention. If multiple branches are found, an index number must be provided.
 
 ARGS:
-  -f, --fetch     run "git fetch" first
-  -d, --delete    delete existing branch first
+  -f, --fetch     run "git fetch" first; else one runs in the background
+  -d, --delete    delete existing branch first, discarding local commits
   -h, --help      print this information and exit
 EOI
         return 1
@@ -29,6 +29,7 @@ EOI
 fetch=0
 delete=0
 ticket=
+branch_index=
 
 while [ $# -gt 0 ]; do
     arg="$1"
@@ -50,10 +51,15 @@ while [ $# -gt 0 ]; do
             exit
             ;;
         *)
-            [ -z "$ticket" ] || {
+            if [ -z "$ticket" ]; then
+                ticket="$arg"
+            elif [ -z "$branch_index" ]; then
+                branch_index="$arg"
+                [ $branch_index -ge 1 -a $branch_index -le 100 ] \
+                    || fail "Invalid branch index: a value between 1-100 expected"
+            else
                 fail "Ticket $ticket already specified"
-            }
-            ticket="$arg"
+            fi
             ;;
     esac
 done
@@ -74,13 +80,26 @@ cur_branch=$(git rev-parse --abbrev-ref HEAD) \
 # make sure we find the branch requested -- and only one
 branches=$(git branch -a | grep "remotes/origin/[^/]\+/$ticket/")\
     || fail "Failed to locate a branch for ticket $ticket"
-[ $(echo "$branches" | wc -l) -eq 1 ] \
-    || fail "Multiple remote branches found:\n\n$branches"
+[ $(echo "$branches" | wc -l) -eq 1 ] || {
+    # we better have an index to confirm that we know we want a specific branch
+    [ -z "$branch_index" ] && {
+        expanded=
+        ctr=0
+        for branch in $branches; do
+            let ctr++
+            expanded="$expanded\n  $ctr. $branch"
+        done
+        fail "Multiple remote branches found; branch index required:\n$expanded"
+    }
+    # pick out the specific branch
+    branches=$(echo "$branches" | sed "${branch_index}q;d")
+}
 # and parse out the branch name
 branch=${branches##*origin/}
 
-# make things easy on ourself and ensure we're at master first
+# make things easy on ourself and pivot to master
 # otherwise you can't delete a branch you're in to pull updates easier
+# it also helps avoid abandoning local changes
 [ "$cur_branch" == "master" ] \
     || git checkout master >/dev/null \
     || fail "Failed to center onto 'master' branch"
